version: '3.7'
services:
  wireguard-client:
    image: wireguard-stop-russia
    deploy:
      replicas: "$REPLICA_COUNT"
      restart_policy:
        condition: on-failure
    
    environment:
      - NET_LOCAL
      - WIREGUARD_PORT
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - ${WIREGUARD_CLIENT_CONFIG}:/etc/wireguard/wg0.conf:ro
